version: "3.8"
services:
  api-instagram:
    build:
      context: .
    image: pipegram-flask:latest
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
    env_file:
      - .env
    environment:
      - PORT=3000
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3000", "--workers", "2"]
    restart: unless-stopped
