version: "3.8"
services:
  api-instagram:
    build:
      context: .
    image: pipegram-flask:latest
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
    env_file:
      - .env
    environment:
      - PORT=3000
    command: ["gunicorn", "--bind", "0.0.0.0:3000", "--workers", "2", "app:app"]
    restart: unless-stopped
